### ISSUE TITLE
Restrict Menu Scan lists when not logged in

### ISSUE THREAD

**Issue by MaxwellDPS** [ScanOC/trunk-player#100]
Howdy,

Would it be possible to restrict the scan lists menu and the talk groups menu from listing, when the user is not signed in?

**Comment by s3m1s0n1c** [comment]
Sorry for the long delay..

You could use something like below in radio/templates/radio/site_live_nav.html
```
  {% if user.is_authenticated %}
 <ul id="menu-scanlist" role="menu" class="dropdown-menu">
               <li class = "divider"></li>
                 <li><a href="/userscan/">Custom Scan List</a></li>
            </ul>
         </li>
   {% endif %}
 ```  
  
  Off the top of my head.. I haven't tested it so u'll have to play around with it..
  
  Thanks
  Sonic

**Comment by MaxwellDPS** [comment]
Duplicate of #63
