### ISSUE TITLE
Docker file for dreinhold/base-django

### ISSUE THREAD

**Issue by MaxwellDPS** [ScanOC/trunk-player#103]
Hey @dreinhold, 

Can we get the docker file for dreinhold/base-django image?

**Comment by dreinhold** [comment]
Hmm, Its set as a private repo. And I am not sure why I would have done that, I dont see anything in it, but I think it started life for non open source job, maybe that's why. Ill share it with you, while I double check there is nothing keeping it from being public.

**Comment by MaxwellDPS** [comment]
@dreinhold Much appreciated sir!
