### ISSUE TITLE
Anonymous Listening - Disable

### ISSUE THREAD

**Issue by kcwebby** [ScanOC/trunk-player#21]
I think it would be nice to be able to set the Anonymous_Time setting to something that completely disables it.

Currently, I have mine set to 0.00001, which essentially does that, but doesn't quite fit the bill as the message states "You are not currently logged into the system. You will only see the last 1e-05 minutes of history. Login or Create a free acount to see more history."

**Comment by dreinhold** [comment]
Use `ANONYMOUS_TIME = -1` to disable anonymous access.
The message then shows :
"You are not currently logged into the system. Login to access the system."

**Comment by imagesafari** [comment]
This doesn't seem to work in the latest release. What is the easiest way to require a login to see anything?

**Comment by dreinhold** [comment]
Try adding to your local settings
OPEN_SITE = False

**Comment by imagesafari** [comment]
That does not seem to make a difference
