### ISSUE TITLE
Track Patches in Log

### ISSUE THREAD

**Issue by kcwebby** [ScanOC/trunk-player#22]
Patch Tracking
Probably dependent on trunk-recorder to support this.

Enhance patch tracking in the interface...   
When its assigned / removed and which talkgroups are involved in the patch.

This would help prevent multiple recordings on different talkgroups when they are patched.
Could record as "TG XXXX, TGXXX, TGXXXX as Patch XXX" and

**Comment by dreinhold** [comment]
Yep, if its not in the json, or if you don't feed it another way trunk player cant do anything about it.

**Comment by dreinhold** [comment]
Im closing this one. If trunk-recorder starts recording the patches then we can add it.
