### ISSUE TITLE
Socket "reload" causes scan interuption

### ISSUE THREAD

**Issue by kcwebby** [ScanOC/trunk-player#25]
When listening to a busy scan list, its observed that upon a "query" of the socket data, an already playing transmission would be interrupted if the volume of new transmissions is high enough that the playing transmission would be moved of pg1.

**Comment by dreinhold** [comment]
Good point. As the query is for the newest 50 transmissions if you are more than 50 behind you will end up at the 50th one.  
The prepossessed fix in #23 to make the query append the data to the page would solve this.
