### ISSUE TITLE
Talkgroups Listing /talkgroups/ && Scan List TG Listings

### ISSUE THREAD

**Issue by kcwebby** [ScanOC/trunk-player#26]
Should include a way to sort list, and needs to include the system ID (or name) so reused TGID's from multiple systems can be identified.   I think this was a miss from the multi-system enhancements.

Same goes for the /admin/ links where you are setting up Scan lists and Menu Scan Lists, should be able to sort/filter by System ID (Or name)

**Comment by dreinhold** [comment]
I think I got them now.
