### ISSUE TITLE
Feature Request: Sort by Date, length, tg, etc...

### ISSUE THREAD

**Issue by MaxwellDPS** [ScanOC/trunk-player#33]
I think it would be great to add sorting on scanlists!
by some of theses... Let me know if you have more below

- Date/time

- length

- Talk group

- System

**Comment by dreinhold** [comment]
Not sure on this one.

So if I sort by length would it sort ALL transmissions by length?
Talkgroup wouldn't that just be the talkgroup page?

System yeah I could see that. But really that could just be a scan list.

**Comment by MaxwellDPS** [comment]
Yeah, my bad in retrospect... I would like to see a way to filter in a scan list or talk group by date/and time... instead of having to go back 12 or 20 pages :) also a way to filter by unit ID would be great too.

**Comment by dreinhold** [comment]
There is an undocumented feature to filter by units/

/unit/<name-of-radio-id>/

For the name you need the "slug" from the unit setting (just the name in lowercase and [ - ] for any spaces.

**Comment by dreinhold** [comment]
So this is more of an advanced search feature, which yes we need...
