### ISSUE TITLE
Unitrunker EDACS intergration

### ISSUE THREAD

**Issue by MaxwellDPS** [ScanOC/trunk-player#44]
Hey,
I have made a program that makes unitrunker integration super easy
https://github.com/MaxwellDPS/Unibridge
![image](https://user-images.githubusercontent.com/11069376/35748867-1f7ea31c-0815-11e8-8aa1-b5c3a8e144ac.png)
![image](https://user-images.githubusercontent.com/11069376/35748913-43530332-0815-11e8-8c96-75371dfc000f.png)

**Comment by dreinhold** [comment]
Max I don't think you needed any changed in trunk player, so i am closing this.. Good job on your utility.
If you want to send a pull request with an update README to point to your project go for it...
