### ISSUE TITLE
User accounts aren't being updated when they subscribe to paid plans

### ISSUE THREAD

**Issue by gavinrozzi** [ScanOC/trunk-player#53]
Currently experiencing this problem with my instance of trunk-player. I have created a few different paid plans (https://ocradio.live/plans/), and users have been able to sign up for them without issue.

Recently, all new subscriptions have not been updating the user accounts of paid subscribers. While they show up just fine as customers in the administrative interface, their accounts are not being updated to reflect the additional level of access. For example, someone signs up for a plan that allows 24-hours access, yet their account is still showing as "free" despite the charge successfully going through and showing up on Stripe. This has required me to manually go in and update their accounts.

**Comment by dreinhold** [comment]
In stripe do you have pending web hooks? Did your domain change, Try a test web hook from stripe.

**Comment by gavinrozzi** [comment]
Ah! Looks like that was the problem after all. Thanks for your help.
