### ISSUE TITLE
Download Audio File link broken when audio files are local

### ISSUE THREAD

**Issue by imagesafari** [ScanOC/trunk-player#61]
When using local audio files and setting AUDIO_URL_BASE to /audio_files/ the "Download Audio File" menu link breaks.

It looks like the urlopen call to download the file in the view isn't getting a hostname. I'm not sure how to fix this, and I'd prefer not to be hacky about it.

**Comment by dkettmann** [comment]
Had the same issue here.  Have figured out a workaround where you can click on the link to the .mp3 (that works) and do "Save file as" but that's not a fix per se.

**Comment by imagesafari** [comment]
@dkettmann Agreed, that is a workaround, and in fact was how we did it before there was a download menu option.

**Comment by dreinhold** [comment]
Give this commit a try 5c132da
