### ISSUE TITLE
Rebuilding the Wiki

### ISSUE THREAD

**Issue by s3m1s0n1c** [ScanOC/trunk-player#68]
Anyone have any objections if I rebuild the wiki using Dan's Install notes and make it nice n pretty.

Something similar to the one I did for pagermon
https://github.com/pagermon/pagermon/wiki

Feel free to comment if you want anything added..

Cheers
Sonic

**Comment by dreinhold** [comment]
No objections at all.

**Comment by dkettmann** [comment]
Sounds great, appreciate any help you can give it, and welcome any additions, edits, corrections etc. Thanks

**Comment by s3m1s0n1c** [comment]
This has now been completed..

I have backed up the old wiki as well.

Sorry Its taken so long..

Thanks
Sonic

**Comment by dreinhold** [comment]
Thanks for working on this!!!
