### ISSUE TITLE
Request:  Get call start time from JSON instead of file name.

### ISSUE THREAD

**Issue by gofaster** [ScanOC/trunk-player#75]
Instead of the file creation time encoded within the file name, get the call start time from the JSON metadata.  
Edit: To add some background.  I made a small change to trunk-recorder that more accurately reflect call start time for conventional analog and conventionalP25 calls; compared to the original which was the end of the last recording/file creation time.  Sometimes there can be long gaps between this time and when the next call actually starts.
The updated call start time is sent within the JSON metadata.  I did not want to mess with renaming the file in trunk-recorder or changing the file creation logic.

**Comment by MaxwellDPS** [comment]
@gofaster This has be fixed in release v0.1.3
