### ISSUE TITLE
Consider switching to mejs from jplayer

### ISSUE THREAD

**Issue by imagesafari** [ScanOC/trunk-player#8]
It'd be easier to get a widget with a progress bar, volume, etc using http://mediaelementjs.com/ than it seems to be with jplayer

**Comment by dreinhold** [comment]
Cool I will check it out. I used jplayer for no real reason other than it was the first package I found that I could get to work. So I'm game to swap it out of it make life easier...

**Comment by imagesafari** [comment]
Yeah, I was trying to change how it looked in the nav, to add the volume widget, etc, and was having a heck of a time, so I went looking for other ones :)
