### ISSUE TITLE
scanoc.com layout and style?

### ISSUE THREAD

**Issue by jasweave** [ScanOC/trunk-player#80]
Sorry if it's been asked before...I've looked and can't find if it has.

Is the HTML/CSS/etc available to make trunk-player look like the below?

https://github.com/ScanOC/trunk-player/blob/master/docs/images/trunk_player_main.png

Thank you

**Comment by dreinhold** [comment]
The layout on the image was an older style I had on scanoc.
Look back at the css in around this time https://github.com/ScanOC/trunk-player/tree/cc26294abda36973af1c36366ea8607b18cee135/radio

If you add 
`COLOR_CSS = 'orange.css'`
Into your settings_local.py file you would get the more current one.

**Comment by jasweave** [comment]
Perfect.  Thank you!
