### ISSUE TITLE
Unable to add cities

### ISSUE THREAD

**Issue by e850205** [ScanOC/trunk-player#83]
First of all, "cities" is spelled wrong.

But most importantly I am unable to add a city because it isn't parsing the google maps URL correctly. 

Entering this URL: https://goo.gl/maps/RfvwnemZfVXZQgxL7

Returns this error: 
Enter a valid URL.
Ensure this value has at most 400 characters (it has 3838).

**Comment by kcwebby** [comment]
Curious, what are you using Cities for?
I don't think its implemented on the front yend  yet, is it?
