### ISSUE TITLE
Changing Date from mm/dd/yyyy to dd/mm/yyy

### ISSUE THREAD

**Issue by s3m1s0n1c** [ScanOC/trunk-player#90]
Is the date format hard coded?

How does on change it?

I've set timezone and tried USE_I18N  & USE_L10N

Thanks
Sonic

**Comment by RadioTechGuy** [comment]
@dreinhold if we updated :
https://github.com/ScanOC/trunk-player/blob/cb3694a592316aa462dc412fccffab47fa7f4134/radio/models.py#L213
to read the string format from a setting would that work?

**Comment by dreinhold** [comment]
@RadioTechGuy yes that would work out good. Then people can put whatever they want in the format.

**Comment by s3m1s0n1c** [comment]
@RadioTechGuy Thanks man..

Never thought to look for it in the models.py

Merry Christmas
