### ISSUE TITLE
Import/Export Radio Units using manage.py

### ISSUE THREAD

**Issue by s3m1s0n1c** [ScanOC/trunk-player#97]
Would be awesome to have a Import/Export function on manage.py for radio units.

I have been busy collecting and want to import my list into the system

Thanks
Sonic

**Comment by dreinhold** [comment]
I did not know this was not already in here. Added the files in 6fbb8eb5f

**Comment by s3m1s0n1c** [comment]
Thank You :) 

LEGEND!!
